# 头部菜单，title: link
menu:
  Github: https://github.com/HanyuuFurude
  Skylark-Studio: https://github.com/orgs/Skylark-Studio
  mail: mailto:HanyuuFurude@outlook.com
  leetcode: https://leetcode.com/hanyuufurude/
  csdn: https://me.csdn.net/SkylarkStudio
  zhihu: https://www.zhihu.com/people/Skylark_Studio/activities
  \[Mr.Chen就素小朋友\]: https://encofcomic.github.io/


# 是否显示目录
TOC: True

# 是否自动播放音乐
autoplay: false

# 默认音乐
mp3:
  - https://raw.githubusercontent.com/HanyuuFurude/TechBlog/master/Others/music.mp3

# 首页封面图, 为空时取文章的cover作为封面
# welcome_cover: img/Hanyuu_Paint_origin.jpg
welcome_cover: img/welcome-cover.jpg

# 默认文章封面图
# cover: /img/cover.jpg
cover: /img/covers.jpg

# 是否关闭默认滚动条
scrollbar: True

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    # 是否自动展开评论框
    autoExpand: false
    # 应用编号
    clientID: ''
    # 应用秘钥
    clientSecret: ''
    # issue仓库名
    repo: ''
    # Github名
    owner: ''
    # Github名
    admin: ['']
    # Ensure uniqueness and length less than 50
    id: location.pathname
    # Facebook-like distraction free mode
    distractionFreeMode: false

# 网站关键字
keywords: Hanyuu

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics:

# 网站ico
favicon: /img/favicon.png

# rss文件
rss: atom.xml